-- MySQL Script generated by MySQL Workbench
-- Sat May  6 00:56:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_clientesclientesSQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema compra-venta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema compra-venta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `compra-venta` DEFAULT CHARACTER SET utf8 ;
USE `compra-venta` ;

-- -----------------------------------------------------
-- Table `compra-venta`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idclientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra-venta`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` FLOAT NULL,
  `cantidad` FLOAT NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra-venta`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `precio` FLOAT NULL,
  PRIMARY KEY (`idcompra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra-venta`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`factura` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(10) NULL,
  PRIMARY KEY (`idfactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra-venta`.`detallecliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`detallecliente` (
  `clientes_idclientes` INT NOT NULL,
  `factura_idfactura` INT NOT NULL,
  PRIMARY KEY (`clientes_idclientes`, `factura_idfactura`),
  INDEX `fk_clientes_has_factura_factura1_idx` (`factura_idfactura` ASC) VISIBLE,
  INDEX `fk_clientes_has_factura_clientes_idx` (`clientes_idclientes` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_has_factura_clientes`
    FOREIGN KEY (`clientes_idclientes`)
    REFERENCES `compra-venta`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_has_factura_factura1`
    FOREIGN KEY (`factura_idfactura`)
    REFERENCES `compra-venta`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra-venta`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`detalleventa` (
  `factura_idfactura` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`factura_idfactura`, `producto_idproducto`),
  INDEX `fk_factura_has_producto_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_factura_has_producto_factura1_idx` (`factura_idfactura` ASC) VISIBLE,
  CONSTRAINT `fk_factura_has_producto_factura1`
    FOREIGN KEY (`factura_idfactura`)
    REFERENCES `compra-venta`.`factura` (`idfactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_has_producto_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `compra-venta`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra-venta`.`detallecompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`detallecompra` (
  `compra_idcompra` INT NOT NULL,
  `producto_idproducto` INT NOT NULL,
  PRIMARY KEY (`compra_idcompra`, `producto_idproducto`),
  INDEX `fk_compra_has_producto_producto1_idx` (`producto_idproducto` ASC) VISIBLE,
  INDEX `fk_compra_has_producto_compra1_idx` (`compra_idcompra` ASC) VISIBLE,
  CONSTRAINT `fk_compra_has_producto_compra1`
    FOREIGN KEY (`compra_idcompra`)
    REFERENCES `compra-venta`.`compra` (`idcompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_has_producto_producto1`
    FOREIGN KEY (`producto_idproducto`)
    REFERENCES `compra-venta`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra-venta`.`dc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`dc` (
  `c` INT NOT NULL,
  `f` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra-venta`.`dv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`dv` (
  `p` INT NOT NULL,
  `f` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `compra-venta`.`co`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compra-venta`.`co` (
  `c` INT NOT NULL,
  `p` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
